// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateVIP(arg1) {
  return window['go']['main']['App']['ActivateVIP'](arg1);
}

export function AnalyzeDrive(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeDrive'](arg1, arg2);
}

export function AnalyzeQuickScan() {
  return window['go']['main']['App']['AnalyzeQuickScan']();
}

export function CheckTrialStatus() {
  return window['go']['main']['App']['CheckTrialStatus']();
}

export function CleanCategories(arg1) {
  return window['go']['main']['App']['CleanCategories'](arg1);
}

export function ClearAnalyzerCache() {
  return window['go']['main']['App']['ClearAnalyzerCache']();
}

export function DeactivateVIP() {
  return window['go']['main']['App']['DeactivateVIP']();
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function DeletePaths(arg1) {
  return window['go']['main']['App']['DeletePaths'](arg1);
}

export function ExpandNode(arg1) {
  return window['go']['main']['App']['ExpandNode'](arg1);
}

export function GetAnalyzeProgress() {
  return window['go']['main']['App']['GetAnalyzeProgress']();
}

export function GetAnalyzeStatus() {
  return window['go']['main']['App']['GetAnalyzeStatus']();
}

export function GetAnalyzerMinSize() {
  return window['go']['main']['App']['GetAnalyzerMinSize']();
}

export function GetCacheStats() {
  return window['go']['main']['App']['GetCacheStats']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDiskUsage() {
  return window['go']['main']['App']['GetDiskUsage']();
}

export function GetLastAnalyzeTime() {
  return window['go']['main']['App']['GetLastAnalyzeTime']();
}

export function GetScanProgress() {
  return window['go']['main']['App']['GetScanProgress']();
}

export function GetScanStatus() {
  return window['go']['main']['App']['GetScanStatus']();
}

export function GetUnusedFiles(arg1, arg2) {
  return window['go']['main']['App']['GetUnusedFiles'](arg1, arg2);
}

export function GetVIPStatus() {
  return window['go']['main']['App']['GetVIPStatus']();
}

export function GetWhitelistDirs() {
  return window['go']['main']['App']['GetWhitelistDirs']();
}

export function IsAutoAnalyzing() {
  return window['go']['main']['App']['IsAutoAnalyzing']();
}

export function ResetTrial() {
  return window['go']['main']['App']['ResetTrial']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanForJunk() {
  return window['go']['main']['App']['ScanForJunk']();
}

export function SetAnalyzerMinSize(arg1) {
  return window['go']['main']['App']['SetAnalyzerMinSize'](arg1);
}

export function ValidateActivationCode(arg1) {
  return window['go']['main']['App']['ValidateActivationCode'](arg1);
}

export function VerifyActivationCode(arg1) {
  return window['go']['main']['App']['VerifyActivationCode'](arg1);
}
